/*
    {titulo: "",
     ano: "",
     tamanho: "",
     idade: "",
     desc: "",
     img:""
    },
*/

var novseries = [
    {titulo: "Katy Keene",
     ano: "2020",
     tamanho: "1 temporada",
     idade: "14",
     desc: "Acompanhe a movimentada vida da futura lenda da moda Katy Keene e de seus amigos. À medida que se aventuram na cena de arte de Nova York, eles encontram mais do que uma carreira na cidade grande: encontram também amizade duradoura.",
     img:"https://bn02pap001files.storage.live.com/y4miFNU0C-BhbeMqpWEbCjRdt9DE0kgyc254JW0npwKnvcq4DTjWeuPgfoatZQYhkKtB2BBhuaHV3iF6C-Jyp6TlFhoqciEXAE6GmirtJp7RGVgS4r6yWMku_nEf7_lPSYIoB2hxCH175Ua3kkFOVIq9siBZ0EefNI1DsPTBdEUU92Kgj1wxxQ9W2hEGAuP1IPB?width=667&height=1000&cropmode=none"
    },
    {titulo: "Chapelwaite",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "14",
     desc: "Na década de 1850, o capitão Charles Boone muda sua família para sua casa na cidade de Preacher's Corners. Charles logo terá que enfrentar os segredos da história de sua família e lutar para acabar com a escuridão.",
     img:"https://bn02pap001files.storage.live.com/y4mLlAIkzcEzp1BKkCeDqak_wOktCY5N20_sJOHLceI_OvUBdqZydtKfKcra5VNVQDbXNnFupKTuCNgtaX69KitFNESgL5ixcuWGsbnxrWLyz16Bai3cMWdf3BkVRieepnS53s0jK3rrUmRf2wC31fRGoccWhOD2LdEptyS3zX-9F6JqN-bpiqFu9zvpWyG7ug_?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Chair",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "14",
     desc: "A primeira mulher a assumir o cargo de diretora de uma renomada universidade enfrenta os desafios de comandar uma instituição em crise enquanto tenta equilibrar sua vida pessoal e amorosa.",
     img:"https://bn02pap001files.storage.live.com/y4mSaAXPrJ7AveE0AZYQt_AA7-l3QZfLxgbuu_Yg6mJn6GF2SX0A3lQBle_JdpqvVJns1lc9HIOy41IE67P18_kD3gVtC0QTPwh6hkb_4IqqDQ6QRyz9aliT1u3I4D6yjP7oILjnphH1_3z_roZPtFEWeL4vcBUFdd5RIOtzwi85QujcsEP6XXDrvIzSbFZQQQF?width=667&height=1000&cropmode=none"
    },
    {titulo: "Amend: The Fight For America",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "16",
     desc: "Série documental de seis partes sobre a décima-quarta emenda à Constituição dos Estados Unidos. Em 1868, ela prometeu liberdade e proteção igualitária para todos, sendo o marco mais duradouro da democracia do país.",
     img:"https://bn02pap001files.storage.live.com/y4mEsg2EVl1YrLATKshFc0NYE-sY7o7-A9k3agR1OhB_1DOlw8OaKnDEy2z379BAx30457gwzs2_b8BgjVtjwgtJQE7w1-QtmfgrEdPQzyVi10b8x_-XfevQ1G23SqpkB45GZrhZg_INx5MhkjOYFdpTELdHmjl68xRsBLYJlqtYFY8IO4QsQy6HR7Xxln0eGlb?width=667&height=1000&cropmode=none"
    },
    {titulo: "Starstruck",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "18",
     desc: "Um millennial em Londres fazendo malabarismos com dois empregos sem saída e navegando na manhã estranha após a noite anterior, quando descobre as complicações de dormir acidentalmente com uma estrela de cinema.",
     img:"https://bn02pap001files.storage.live.com/y4mwjaRDuTXnsMiuAL1r2G67Oe9WXjNpKbQwnlfUAVaiIJOTApq86-MD-h5vVSlZ45L6JwpiNwl5BN5akuC-wvmGXNt0hDlJ9i0HaBTjS4Bh219cg2jFukW-r3wHsDxtrNWGmag0HDjrG2bBrBiRyh32g_1Aixwn4J-1x9ZY6GgUFX3iR92LyvyWl8jKFmxcw5J?width=667&height=1000&cropmode=none"
    },
    {titulo: "Fantasy Island",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "14",
     desc: "Pessoas que entram avidamente, mas acabam renascendo para si mesmas através do realismo mágico da Ilha da Fantasia.",
     img:"https://bn02pap001files.storage.live.com/y4mEvOkSUA5sU3lwROajDkoPCzd4KqKHe2j5B8PHlA_1v4wLGexxA3viwc7iOh2JAXKFcrjV2kEM--SuSA6413R1qjSTrllBv__WDPQdK7sxQgsDpJZur5tiTZc0h6ZX_MMrlGh1U1MX-uqyhGO7NE1uFkXDN0XCgwaJ9rF8kixyOSWWm8fXuEeang6cv3oFwiI?width=667&height=1000&cropmode=none"
    },
    {titulo: "A Discovery of Witches",
     ano: "2018",
     tamanho: "2 temporadas",
     idade: "14",
     desc: "Diana Bishop, historiadora e bruxa, embarca em uma jornada mágica após descobrir um manuscrito em Oxford. Para proteger o livro, ela conta com a ajuda de um vampiro misterioso.",
     img:"https://bn02pap001files.storage.live.com/y4mFpfof9kG8DrO4X3DnMl7SIrgWpd1dvv4Xc3W9Vl25usfOYDSGhksbHEjZcsCg-IF5dFd-LajSPQnhQoR5i5rzeaQziowiJIDQUMRxgD_makIavwBD5Fh5C7xFBLj4bHwJ3jV8T1s9DDlwpgPsVq2gsoQP99sWRLOo4dfwgN4p8lfHlzQG_xD76MjTpDql59O?width=667&height=1000&cropmode=none"
    },
    {titulo: "Hemingway",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "14",
     desc: "Explore o meticuloso processo pelo qual Hemingway criou algumas das obras de ficção mais importantes das letras americanas.",
     img:"https://bn02pap001files.storage.live.com/y4mZ5004-Kg6_cdXYCys2ZplmTj86-xDuv_mhf0IJ8s_Xzo8L7iZTBQeuD7rsNc8u_HF-JtTuVdinzVobnhw7hck-9vzFlzeuT4__4ty4K9pRsISKb8c9GFyVnnFS0HGm1QfUCOEgT9E8EH_y6a9z8YGLEfC0I62xmjZnrEMHxrFri7yUw2LmG6OG9oiepE6kHV?width=667&height=1000&cropmode=none"
    },
    {titulo: "Westworld",
     ano: "2016",
     tamanho: "3 temporadas",
     idade: "16",
     desc: "Westworld é um parque de diversões futurista que permite a seus visitantes viverem suas fantasias utilizando uma consciência artificial. Não importa o quão ilícita a fantasia pode ser, não há consequências para os visitantes do parque.",
     img:"https://bn02pap001files.storage.live.com/y4mqKNFpcPd6s3AwM_j8Ux3ZSz_X4nxPYhyxTa917xtFXYED-hXsaRbKlcdZcMlds5moaAuW4NUvNBDpP01-LA3W60tUPChhqjZDvBHpzgrjtxF5ARJD6Zfk0kmgtLoY-tk5o7k7akshgDVQkgjEMbRA_c25jJJ9UW3UjHJBEi3Foy6QzOLqdujNGs45JnHb4pm?width=667&height=1000&cropmode=none"
    },
    {titulo: "Debris",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "16",
     desc: "Dois agentes, de continentes e mentalidades diferentes, devem trabalhar juntos para investigar detritos de uma espaçonave alienígena que caiu na Terra e causou efeitos misteriosos na humanidade.",
     img:"https://bn02pap001files.storage.live.com/y4mTtz7w7a-PQPgTvPrZSE0Eq-p037K9664qAZEQS_hNcRD7ZU71vrMhU_Ub_w8ZBSt3CKUoT0xLDgaCflttIrAKFDFT0DvPo4bzHNRV2Fn-rteYjbahHdadz1CMpTKqy9rK34gQznors1T9yBLtV0fMudykev6iW2G3i8QnqpqaeTRfHvGCUZa6H5-Tx6ajkFv?width=667&height=1000&cropmode=none"
    },
    {titulo: "Behind Her Eyes",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "16",
     desc: "Louise tem um caso com o chefe, o psiquiatra David, mas sua vida muda de rumo depois que ela faz amizade com a esposa dele, Adele, e se envolve em uma rede de segredos, mentiras e dissimulações.",
     img:"https://bn02pap001files.storage.live.com/y4msZphJW_IAv8ST_2aKwdlsNXDMrQfeZq2G9te_wmQFYmgATa3ldruhs-NJn6OZI71zP2CLANLnFYVgazIXrBf6EPY_97odxWrC1LF3vwRV1WlMnyXZLm4nrFTbGBcSznkCGINOCfHzuKmxyIkTC6kffeH0RCtVigS4Oery71sb0KoiF6yTbVt-BIdxzMTIIDC?width=667&height=1000&cropmode=none"
    },
    {titulo: "Home Before Dark",
     ano: "2020",
     tamanho: "2 temporadas",
     idade: "16",
     desc: "Uma jovem da cidade descobre pistas sobre um caso não resolvido enquanto visitava a pequena cidade à beira do lago.",
     img:"https://bn02pap001files.storage.live.com/y4msxd_wOLXOni-GlyIlGRoYDnAwc2rgpfGSdyXSbpN7KcOY240USmqAL-zGVr46DptQ84dgjevWvQGXqbYog_24Nka95X2tscB6eC9MgfWyagBbRhyYApDyGEFNBrDPuoXW0pUDKYlUar1WLH1nLq5-KwqPksldSiHB-i6re1D72IhyW9WlHehbCevjdrV-RbL?width=667&height=1000&cropmode=none"
    },
    {titulo: "Lisey's Story",
     ano: "2021",
     tamanho: "1 temporada",
     idade: "18",
     desc: "Uma viúva se torna alvo de um perigoso perseguidor que está obcecado com o trabalho de seu marido.",
     img:"https://bn02pap001files.storage.live.com/y4mVZxuFGk2wN50XPHpvALqhan_ywiFXA0JQ4PgyC__tnfJMOo_roK4pOdYSh6faqKWmyKGPffcAORwFA8_G70PlaxFLArrg06hJnNQ48E-Fpan8oX6BWid6jO4OtDuIorjXf33BZOwJqEMH0bZsF1fN1hjpkD63YDkbCItKDe1TUXdjQm7c99V0J7-XDsrWS0j?width=667&height=1000&cropmode=none"
    },
    {titulo: "Euphoria",
     ano: "2019",
     tamanho: "1 temporada",
     idade: "18",
     desc: "Um grupo de estudantes do ensino médio lida com diferentes situações típicas da idade como drogas, sexo, busca pela identidade, traumas, comportamento nas redes sociais e amizade.",
     img:"https://bn02pap001files.storage.live.com/y4mNUsDWu8XklzZ2fcD3eMrVh6yp14ny1H6O992j3u6W5R_xItFGz-q9PdtaWUSSOZx-T3JE2AMiCu2b7wKmheYeBy73H9OMQ52rzN1VF0lV6X7Q8HZEViD0GDfNk-iT15yA_IjFQ75P8vj7DgDrbXfxxiMYwIt7pbnZa1M8-4MGnEvd-pB72zS-J4A5F70QH5j?width=667&height=1000&cropmode=none"
    },
    {titulo: "Riverdale",
     ano: "2017",
     tamanho: "5 temporadas",
     idade: "14",
     desc: "Enquanto navega pelas turbulentas águas do romance, da escola e da família, Archie e seus amigos ficam enredados em mistérios escuros.",
     img:"https://bn02pap001files.storage.live.com/y4mqvJjXkCTplTWTHeRaYPUuWw0ZX7fYX6VcJ6UhngM7RxHpBQH9siCWVIZRfOr38O4I1AG5upENfNiZqO5X1TGS_p1Ic16ksudAakcdkoG9FDAGABY6NFwSM1leKx0YdW0WS6OF414z_B9QpGq0MXWjJRpi2YuDO56LgIOVaHeK6BJfQrzL4CrmdpEfGXgHPrV?width=667&height=1000&cropmode=none"
    }
];

let novfilmes = [
    {titulo: "Jolt",
     ano: "2021",
     tamanho: "1h 31min",
     idade: "16",
     desc: "Lindy é uma mulher com um grave problema de raiva que se controla com a ajuda de um colete de choque. Depois que o homem pelo qual se apaixona é assassinado, entra em um estado de fúria na busca pelo assassino.",
     img:"https://bn02pap001files.storage.live.com/y4m6v_pvA4TUcJ8TcFJzn90q7YmL0D9rmPNXpm_qYlFplh69qJjY2HTE-o3rmJlSQhlhe1iQE38TzW1bhFbNtax5sX65AWIV2tUQdiaPl80n-g8NIQuFzM9amA30JGBlXi2EVjT3vx3R3yY33kG8vptKqed8ZOPh5E7mO18Ee3tUo7rYGH6bxLs9YFW4PhvH4sU?width=667&height=1000&cropmode=none"
    },
    {titulo: "Raya and the Last Dragon",
     ano: "2021",
     tamanho: "1h 47min",
     idade: "L",
     desc: "Em um reino conhecido como Lumandra, uma Terra reinventada e habitada por uma civilização antiga, um guerreiro chamado Raya está determinado a encontrar o último dragão.",
     img:"https://bn02pap001files.storage.live.com/y4mSnSWagZNVlNoLd9_pya4FZo-Jo_-vXrdfUNBPKQcujM7AevkN8fRK1ITI8bZ0Sg1PSpY84-M0vFaj3ZeiJ4V3PcEPw-BQUjqI8aIABDYkqFsU5XHt3_tr9DdvBau4_pIGEJXkfLaE_hTfw15yrWDjdO5r8x3ifPLfz6bxeGxUSo5CgtpqxTwbyuTIRB59y4B?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Little Things",
     ano: "2021",
     tamanho: "2h 8min",
     idade: "16",
     desc: "O vice-xefire do condado de Kern, Joe Deacon, é enviado a Los Angeles para o que deveria ser uma rápida tarefa de recuperar uma evidência. Ao invés disso, ele se envolve com a busca de um serial killer que está aterrorizando a cidade.",
     img:"https://bn02pap001files.storage.live.com/y4mkAtjDjm3jCgTgnNJGoq7X6hPJGh019tvoCIS3AD5SRSGcbzTVw5mVLudMRIfgIcxT_K3xqOceSEPENq2wlghtRSS3dQvrGeGZzLoC4oJx3t7EPsnsUnOPgDr760PbmNWfkHWx5NFvFGVejXIxrSeGNchZ6wEXzN7wt-ot_8eVMnvxbHV4WLPLVWK4QWGS12l?width=667&height=1000&cropmode=none"
    },
    {titulo: "Nobody",
     ano: "2021",
     tamanho: "1h 32min",
     idade: "18",
     desc: "Um homem intervém para ajudar uma mulher que está sendo assediada por um grupo de valentões e acaba se tornando o alvo de um mafioso.",
     img:"https://bn02pap001files.storage.live.com/y4mpW4fLRIpa8oCLb4GHR4Y0J_b-GoQPTiFhNg02TIOHWjZ9Nf9fSfx5h4RJ0urwAd8hdUZ-6WyyQz0xy_IX_tVshrZdBaTgMdh-RYLS5OHJhZqB43QSFW31Hq0tg6nWUaw71IcT3XuV5tan84vx2lPHlR2PZt3dmGemOo6HUO8Suh1i08ktfx0cpHwu4Zotia5?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Ice Road",
     ano: "2021",
     tamanho: "1h 49min",
     idade: "14",
     desc: "Após o desabamento de mina de diamantes no norte do Canada, um motorista de caminhão precisa liderar uma missão impossível de resgate e dirigir sobre o lago congelado às vésperas da primavera para salvar os mineiros.",
     img:"https://bn02pap001files.storage.live.com/y4mKdmamzeu2w3_-XZQXBY3ibDwlXqLGq1N2dScl2pubLIa1RT9U_imzosoR4L-aKUyP2-b-rQnoN3TG8oIz6NJIMC1tL0fFBfvc8LOuEt8QbAgcayCKvZQFDMkeHsKjJp3_DjxOKKylR6uJeUNHurY-sXIUpyK2ujCmA0SWgU44NSWXpCB-8kVbCjtW1H2aGEN?width=667&height=1000&cropmode=none"
    },
    {titulo: "Wrath of Man",
     ano: "2021",
     tamanho: "1h 59min",
     idade: "16",
     desc: "H é frio e misterioso e trabalha numa empresa de camiões de dinheiro responsável pela movimentação de centenas de milhões de dólares em Los Angeles todas as semanas.",
     img:"https://bn02pap001files.storage.live.com/y4mgLa8pu3HoQAgy1UfW-cB_SRmawTMPAxqVAUKpEnyJqDEyhGIEP0m9WI2b5b1hqjD9q9nA2AJBrFtTuN1dh91UwCDUwophHWRD8sj6uEpWMC454e70Y71hbVAMcgupQIDFsjeSGFBzdKpAghc_3f0KTZkMaILTE-IgoCJZlHAIJNo98aNKkZfy2QUy0NbRnZ5?width=667&height=1000&cropmode=none"
    },
    {titulo: "Stillwater",
     ano: "2021",
     tamanho: "2h 19min",
     idade: "14",
     desc: "Um pai viaja de Oklahoma para a França para ajudar sua filha que foi presa por assassinato",
     img:"https://bn02pap001files.storage.live.com/y4mw4ue0YqgnAf-nqHw1J2TkQMMm40cL_obvg11mLjf8kOs0CO1kusXefzyTmFgXk0TPzfsfo47CvZe9w1FPvncnL1VHOUj_RafKK7rooClq1h1229NXYJGdNACEI7G6SUvD48Pa3NOR5EqPKeixEZACZP3njGXdu9vq0_Q7jPEbTkQvA-DiTdVW0YHvSOMgO1L?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Banker",
     ano: "2020",
     tamanho: "2h",
     idade: "14",
     desc: "História de Joe Morris e Bernard S. Garrett Sr., dois dos primeiros banqueiros afro-americanos nos Estados Unidos.",
     img:"https://bn02pap001files.storage.live.com/y4maInyNi_3QurKE0-baPSQZjjpjX10V-5CxTnDhXu0CBNDpJJAtPNvRS-Gmnbz9utC8FrBikn4HM6B9k6DMAmTlHickHYawrmcRPjNnEw-PPYKLcGZ1NfjwKRynbFFr0Ck-OCjHgOauLcjyk9PItz8MMbOrIyar6GGNeOk_b_b9xhi9wI_lYmbHzbjVvtyC-Y_?width=667&height=1000&cropmode=none"
    },
    {titulo: "Radioactive",
     ano: "2019",
     tamanho: "1h 49min",
     idade: "14",
     desc: "Radioactive é uma história incrível e verdadeira de Marie Sklodowska-Curie e seu trabalho vencedor do Prêmio Nobel que mudou o mundo, estrelado por Rosamund Pike e Sam Riley.",
     img:"https://bn02pap001files.storage.live.com/y4mLtoTpRfJ3XoV1icfpJsAk4RR-Xss7xA3fdkRRHVT-YFmfQCFceZ_NfsmSvgSPIp6W2vb__J_Br5cNgONv18vWgAG03AE1p56K7eXcuE6uAweyjIhBtiVQ7HVo9El14mVlcq4VXV8Kj5sTPEZAJ7-Qhf0ha7MovPABKv8Ok_V2pvpOMR2_H_ubwrGmbXf46-K?width=667&height=1000&cropmode=none"
    },
    {titulo: "Official Secrets",
     ano: "2019",
     tamanho: "1h 52min",
     idade: "12",
     desc: "A verdadeira história de um informante britânico que vazou informações para a imprensa sobre uma operação ilegal de espionagem da NSA destinada a pressionar o Conselho de Segurança da ONU a sancionar a invasão do Iraque em 2003.",
     img:"https://bn02pap001files.storage.live.com/y4mmLg9_w_xvs82JfbdRBM1e4G4GsNfcEZgp2tODQdh7msdG6x9ZUJm__L0HqWF9u_Exg0ET773S7GFXxkyzcJ6Ug2yqqi4KfFi5TYXWEgJHHJeHd3CTQXu_kFOGUVa4sPk8T1Vw2YqDvdtmj4wC4wrV2Kq2E4DDx1Dj53t5vsp5Cf0P886hkbYiEZ7f1s1g1x0?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Report",
     ano: "2019",
     tamanho: "1h 59min",
     idade: "16",
     desc: "Daniel Jones, um membro do Senado encarregado de conduzir uma investigação sobre o programa de detenção e interrogatório da CIA após 11 de setembro, revela segredos chocantes.",
     img:"https://bn02pap001files.storage.live.com/y4mMJb1jXYkboDD5_O8BCsZDmgKpcT0-rsKWPrkFQJaVGjII5oNSfkZ48nrX8NpLklY7GxfNFjGd8qFkszwKgCr4_wxjtMC96vv1FZqf52kXpAwyn-rPQCikz47Enu_g3mUv2nDEQiVD1YES2SS1u6tnHZWthRGYSYuC9PTNqudl9k-DbgnIaa3bpC3s_M-_b3X?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Good Liar",
     ano: "2019",
     tamanho: "1h 49min",
     idade: "16",
     desc: "Em um jogo de gato e rato, o golpista Roy Courtnay não resiste aplicar seu golpe mais uma vez quando conhece a viúva Betty McLeish. Porém à medida em que a mulher abre sua vida ele se surpreende quando começa a se importar com ela.",
     img:"https://bn02pap001files.storage.live.com/y4mCwkRalxDdoD3rjC3Tvfm60gE5PPkeInnlxouYoXbpNXChDzF9CJ7gLVWVJWy9RueuljyFqf65EhpFfihDm1gtYn7baL5kw5iYloyyySCelKxUq-HfvFrW_FZk_aE4gcxftCzm6HqdcVCWxF-1wjtZFHdgVjtmaaEuxQiMmhFmXTPqY15sRWUKLXEe0ZyJawl?width=667&height=1000&cropmode=none"
    },
    {titulo: "Just Mercy",
     ano: "2019",
     tamanho: "2h 17min",
     idade: "14",
     desc: "A historia do renomado advogado de defesa dos direitos civis Bryan Stevenson, enquanto relata suas experiências e detalha o caso de um prisioneiro condenado a morte que ele lutou para libertar.",
     img:"https://bn02pap001files.storage.live.com/y4mCeqbHogiBtUqtNTMI1tjUe5VuNvzOGT41iJ5HSzaz4ItmWx6Gz6IhuX-OL9xTu-ckPNDZd4yr73MylTFY2buK4Xomv1xyWssNfEoH5UOexiXtXE3SupQBwgxQdTNKV2YKBEDhvU-JchhehexLq2Ih01HkKi8GbmtSFDuENZL6xV4CXw_cxWh6FlfENwx1EjM?width=667&height=1000&cropmode=none"
    },
    {titulo: "Dark Waters",
     ano: "2019",
     tamanho: "2h 6min",
     idade: "14",
     desc: "Um advogado corporativo entra com uma ação ambiental contra uma empresa química que expõe uma longa história de poluição.",
     img:"https://bn02pap001files.storage.live.com/y4mTW0nIK7vnRRDL31WM9BoJEnSQ5P-_923AlR80gpoWlM32fqmzY6gIKObbeN-P9B_uMv_fnQFjhiVXLRRtTqXl18yeAOxGNBZFAl00dhyj8GMTiwlMjIZKXV_2yUKCDwyhs8JntJD4MmQ9ROqtChpOP3BqEL-b3AMgglWLsUMagjZxBI3EdyxCVhtOdLa5Y2t?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Mule",
     ano: "2018",
     tamanho: "1h 56min",
     idade: "16",
     desc: "Um horticultor de 90 anos e veterano da Guerra da Coréia se transforma em mula de drogas para um cartel mexicano.",
     img:"https://bn02pap001files.storage.live.com/y4mgkUFfFrA6kH1DOqkn1QWVYhB8K3vB4ZmdUb9OTKheufVkmyBmwhHiQeGOEA-Ntnys0m3IRGjq_74e4vaP2rdECYnyKatBZtMWwMDgwrUAyliEI3vfnX-aEhNYwCGegzdlht4FzGkp47C9YxUpqFfNkEkxvcPS_h_aSJqkL0Zk_YPqPt85y_4mMllkhzSS2rb?width=667&height=1000&cropmode=none"
    }
];

let startrek = [
    {titulo: "Star Trek: The Original Series",
     ano: "1966",
     tamanho: "3 temporadas",
     idade: "10",
     desc: "No século XXIII, a humanidade já desenvolveu a tecnologia para viajar pelo espaço. A bordo da nave estelar USS Enterprise, a tripulação parte numa missão exploratória com duração de cinco anos, em busca de novos mundos e civilizações.",
     img:"https://bn02pap001files.storage.live.com/y4mvKyHva1_ZVx61U4UAjLfFtPf5hmzxkUDTipPDAYClkp7x-39bFcJ1qkDGrRFPh-nrFV2RzNf_O1HQ8rCsXTrHHxarKHMruLnZji-zi7OXlE_jMJDhQsvujfvPtQ5ud5s-jOKcJ_2bVZz6v0d_IJ6xIEHeELcytXiSVUDseg4u26LinhNAefAT8iB0DC9JTSX?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: The Next Generation",
     ano: "1987",
     tamanho: "7 temporadas",
     idade: "14",
     desc: "Décadas após as aventuras da tripulação original, o capitão Jean-Luc Picard lidera uma nova Enterprise em missões por mundos desconhecidos.",
     img:"https://bn02pap001files.storage.live.com/y4mJKtlDrYosnLdirUhQq-bzTMc6miKagMqhztqYCiGGh8R7l3AWiRS8Jfi2FVn5Uh-1kgSaSPnyfw81VpCFMePMr5gwgywaC8R1IPit4HUlK6BM99CGJIw8ARehwrwi3BsP9Abvqsjxa_O1Pp5b70R4EcWE12zPQ83it3ivmjHQ4MacnbEAGak_b70K--LA5qk?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Deep Space Nine",
     ano: "1993",
     tamanho: "7 temporadas",
     idade: "12",
     desc: "Nas proximidades do planeta de Bajor, recém libertado do regime cardassiano, a estação espacial da Federação, Deep Space Nine, protege um buraco de minhoca que leva ao outro lado da galáxia.",
     img:"https://bn02pap001files.storage.live.com/y4m_JcHE44ODnQtvllweYUKthA0rF7DJsX-pNqno42o8xirMz8XmOa4UJpqZvgiE0NOLt-C-RWQnwQTwRn6NTvBLrrzPhll-SeYfre8ghWJr-4WqpK75ivEUexCJrK0YeOCDluxJoXs7KRefsYx3ofcU7BXgtE7HkrZf6UjjXf6zdeWh_iRI2ck4q1w_ZVhTbfW?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Voyager",
     ano: "1995",
     tamanho: "7 temporadas",
     idade: "14",
     desc: "Do outro lado da galáxia, no Quadrante Delta, a 75 anos de distância do espaço da Federação na dobra máxima, a tripulação da nave USS Voyager deve cooperar com rebeldes Maquis para voltar para casa.",
     img:"https://bn02pap001files.storage.live.com/y4mhHibUYR4-qu6ZaZL_5DM-LYjlbplu4adTeFIOKmpJJVSdPM6iPWdeKQDQ0alYPWGSjy2wJXEXeDbVxaEIyo1FnxkP5kz4knY17BhUqiBsgUDvzVIl7bt5KIkqsSnP6xblnZbc4pQWwgQLprW-ugd4z83cEWSz0m7nqPSxCbfd_rHgQLKfdjZA8YAZ87m7Rka?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Enterprise",
     ano: "2001",
     tamanho: "4 temporadas",
     idade: "12",
     desc: "Um século antes da missão de cinco anos do Capitão Kirk, Jonathan Archer, capitão da primeira USS Enterprise, lidera a primeira missão de exploração espacial da humanidade, que levou à formação da Federação.",
     img:"https://bn02pap001files.storage.live.com/y4moj3TpQ64bZifRwqiK0VR6YtuEOrm0zLbabQDQZ7wsOzKb5LV6h4KKIwIYE09YAe7PA45YDzGt5uxqwQw99p46cHT8lGbdOXBiKQGlPqCwmHICZVfOp80ke2a20HoQaTb8Sh6FaYuiMpVyZblzWnm-pr7MgUD3nJZRthvzEhLM87Dit-HM2r78jkEe4Y3d7RZ?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Generations",
     ano: "1994",
     tamanho: "1h 58min",
     idade: "L",
     desc: "A viagem inaugural da terceira nave Enterprise está sob ameaça pelo cientista louco Soren e apenas uma pessoa pode detê-lo, mas ela está morta há 78 anos.",
     img:"https://bn02pap001files.storage.live.com/y4mwdLqz-COYO061hw9qunJAypjG6qHKgh36p1P53vfTaSw88G-P5gbaSVAMN7h-SOkJ9CLcHuJzA5Y5Vp2rPjjI4640Mt5Pb2l9PLCCW3XhBxyUHXJlo70kgnY2AjKuvnV-Q06NawzhiyDq6Pji7glmftB7auu3ym4Qm-38HuhKLsEw0mmn4KhYojC2pnnPOIf?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: First Contact",
     ano: "1996",
     tamanho: "1h 51min",
     idade: "L",
     desc: "O capitão Jean-Luc e a tripulação da Enterprise embarcam em uma nova aventura, enfrentando os Borgs, criaturas meio orgânicas e meio máquinas que formam uma comunidade com um único objetivo: conquistar e assimilar todas as raças.",
     img:"https://bn02pap001files.storage.live.com/y4mQWhxrnEGUGylYK0eHbVNAfwkXCZfd0qmJVkvDAO9j8Vnfg8uFwLrxwaSENlvDB6TXdHGBnVbAwH2pWi_ROZ1s9ATFfEOlh_RkzSakslbVCg4eyEBjUUOqmLoias_0WgvrZGOsYm30nrm4JITB1_9u1zq1jiXeNE1hxe6d0nwd6mctp3ja8vpJ_9vOp013eji?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Insurrection",
     ano: "1998",
     tamanho: "1h 43min",
     idade: "L",
     desc: "Durante uma missão ao planeta Ba'Ku, Data descobre que esta civilização está sendo ameaçada e a tripulação da USS Enterprise se rebela contra a Federação para proteger os habitantes deste planeta.",
     img:"https://bn02pap001files.storage.live.com/y4m-HkvfVhLWYrOZ4YOteeJykzjhmoUT_Y3SjZsAQvpr8PipzFlDxPT5gleNbZgD_88Su6YprGHEcmWAnRjN4OOvTkqCscUmQl1Gkh9VWOJS8rF1kIEzEC65hFQQ6kC3g4aDY5rS10MMHQKnFAv3A87VLZY1WyaNZGY6FuS5HfHa-wtXNEuLpuZPKpu9fM-5fi6?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Nemesis",
     ano: "2002",
     tamanho: "1h 57min",
     idade: "12",
     desc: "A Enterprise, seu capitão e a tripulação partem ao encontro dos romulanos para um acordo de paz, mas um adversário os espera. Ele é nada mais nada menos do que um sósia do capitão Jean-Luc, que se prepara para acabar com o planeta Terra.",
     img:"https://bn02pap001files.storage.live.com/y4mK7pvrh0oLxTYNkW0SfuX09ZJhwuqSR092kr8aXGdvwFYBvLWuFFfDJQnUOxXx5cP30GLk3Lxy_3uVG_hzMW_8ngN8ni_WatDtb05JBVVRaXz5dZcvYAKyy9QAqUDwq94R1gr5uFcf_CdX1k6STs8tDedxmdHOkAxAwvhQY3din6NTPEhBskUVT24lttfgLny?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Discovery",
     ano: "2017",
     tamanho: "3 temporadas",
     idade: "12",
     desc: "Dez anos antes de Kirk, Spock e Enterprise, o USS Discovery e sua tripulação descobrem novos mundos e civilizações enquanto um oficial da Frota Estelar aprende a compreender novas culturas alienígenas.",
     img:"https://bn02pap001files.storage.live.com/y4mniQYd8B01x2gtd9Ep5LZEFquUtkeR5A64jYYDq9uaxicn4wbNTPBkbWALazX8mrDrED3j7RO19AnEkJ2NwWhlSrId4WZ5dogONSqwbiRB-ZvPnvtuduLRBUwaDSva8Ug0zOe7niBNlep8OTQ0qmhZb9LowuwyqDUFroFDEjh5I68RjGjvKJZEZq7SOYfoyIH?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Picard",
     ano: "2020",
     tamanho: "1 temporada",
     idade: "16",
     desc: "A série se passa 18 anos após a última aparição de Jean-Luc Picard em Star Trek: Nemesis (2002), e encontra o personagem profundamente afetado pela morte de Data, assim como pela destruição de Romulus após a supernova de seu sol.",
     img:"https://bn02pap001files.storage.live.com/y4mV9BwIyp0r6C9UEfFyj67btGHCdImV0Fr9g75k9SKX-7DAXBvUoUsoXO-FK0OdBEKMdWpBLCGK2otgYHMbJBu8aVoFjp864y03z0J8ad2da4hqeUE9bXTiXATVAYZgM2PUCL8r80-ZcEbP-xBQ-UsiKt5b9fATdtmoJEXXd0ylEhicgiLoNihIzyDjPtSpdEn?width=667&height=1000&cropmode=none"
    },
    {titulo: "Star Trek: Lower Decks",
     ano: "2020",
     tamanho: "2 temporadas",
     idade: "14",
     desc: "A bordo da USS Cerritos, uma nave pouco conhecida da Federação, a tripulação tem a missão de realizar o segundo contato com novas civilizações, que inclui atividades burocráticas, protocolos e transporte de suprimentos.",
     img:"https://bn02pap001files.storage.live.com/y4me9zKoJyAyANqI-G2hXacEcXYOh_J__7DofUuI_QHCDlojrls8BJUaMVRLUYl1sEo3-MiY9ZgK_rFJns6sJ7eiosN6L8Ad9N8QI55aA6TdGJn6p5OqWVC5eFHzx3oCjSps0oXwPH5XKABlCXC_LQaQU2uUfuOlbQ579psY6qFzdQiJk_6elKOQt5ZZykJCKnJ?width=667&height=1000&cropmode=none"
    }
];

let destfilmes = [
    {titulo: "Interstellar",
     ano: "2014",
     tamanho: "2h 49min",
     idade: "10",
     desc: "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço, na tentativa de garantir a sobrevivência da humanidade.",
     img:"https://bn02pap001files.storage.live.com/y4meTO9EAPWrpzaC6NgcPdTH-Lafb5Fgm0b3zPsXo8u7MPiCax2Fl4dnx3cZlq9pKtU4mjKbD5qIfSSYpSkzRuiEuHRlbMmH0P1q9jZjrW-GsvIaJMBsFiu3lbj07Cid1bfCno7R8VDPveaxjC79aTFi4hui2Ka1oDbU55KcVWmiafEDqEuYRQ1NaEmvXHelQPp?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Dark Knight",
     ano: "2008",
     tamanho: "2h 32min",
     idade: "12",
     desc: "Quando a ameaça conhecida como O Coringa surge de seu passado, causa estragos e caos nas pessoas de Gotham. O Cavaleiro das Trevas deve aceitar um dos maiores testes para combater a injustiça.",
     img:"https://bn02pap001files.storage.live.com/y4mrb3zSZ2OCuvRkkVpOGbKuT5R6lIlRo4diODLBEjo1rosj3q89EmXPMt132OD6_2T0aG76YEoim7W6ciNpCGzIhx3HxiwEPcFsVA6Fd6_9sVnVj5LpgQpfwTmpR1Lnw4-NVxvaMFWzx7BGr7SN0zOjeXlDDo7-88atupqASVmQ9QeuHmpXB1MdeI8GX20KsoW?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Lord of the Rings The Return of the King",
     ano: "2003",
     tamanho: "3h 21min",
     idade: "14",
     desc: "Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.",
     img:"https://bn02pap001files.storage.live.com/y4mT5jXrr8q-D1x97oeuV-0Ggy0jDunTtgruO1WirlnN_i-gMAz3Hcdm4HlF-3bBI3c0hu4_LPZRuZIybMHsUArFq_GBAPreSUOHdfUm014uAG5LnRODno_mlMQdz4LxRzx_BZ-Eqov1t3Fqk9oR53r5hKyQlrrpTFn3qd-bG8wHWNu-gOAV1LAuEH5-EdZ1YOF?width=667&height=1000&cropmode=none"
    },
    {titulo: "The Matrix",
     ano: "1999",
     tamanho: "2h 16min",
     idade: "12",
     desc: "Um hacker aprende com os misteriosos rebeldes sobre a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.",
     img:"https://bn02pap001files.storage.live.com/y4mw9XfHc_3IUYTR7jX3CNiNqv1vrPMbX9vwAcSrVWU9fA5kXoitxIdEwAOAzp9oVr6Oa2-05rKlmxkL9w_HIc5rWQa5cENKiKI9bXt0tGDxbkCRl8LyQBExeEMQ88r68Z1A2FpHZJkBT8NdplGdxM0jP-xmAziFvG8po6nJAxNXHj566fj-RXBeZpZbKQUvCZf?width=667&height=1000&cropmode=none"
    },
    {titulo: "Raiders of the Lost Ark",
     ano: "1981",
     tamanho: "1h 55min",
     idade: "L",
     desc: "Em 1936 o archeologista e aventurero Indiana Jones é contratado pelo governo dos Estados Unidos para procurar pelo Pacto da Arca, antes que os nazistas o tenham primeiro.",
     img:"https://bn02pap001files.storage.live.com/y4m25epN25MdAKR4_5XQKxdB13ZGGE_lMWR9qQP6vpQqQnraLhUf9M0j7HPR3xAswZNo_H_5ew0P-urtbjQGOzN7rnMZaUv7Wo826euIGjpKpw-2QL5AyzWyivyl4pHl8LkTVUjw806sS_bDgEutEPdGvlwWzA989W7oR2G4Q4h5aa4DQU3mLxNeO86Pz6tm8dJ?width=667&height=1000&cropmode=none"
    },
    {titulo: "Inglourious Basterds",
     ano: "2009",
     tamanho: "2h 33min",
     idade: "18",
     desc: "Um plano para assassinar líderes nazistas na França, e liderada por um grupo de soldados judaicos dos Estados Unidos os quais coincidem com os planos vingativos de um dono de teatro.",
     img:"https://bn02pap001files.storage.live.com/y4mXWWooCRf3a5CLaXSIkgPBIHpooBtz86nGdvUUiEWxaK4XWGFe1d908my1m9z-j5cocZ_WHluqbRmBrRqOdVWkDoULOvwemJRecj2-3yj6Iy8xbwSs0OzaI0ChZwfBktyxXG8-qnxMZivRG-2Oxct7Jjg2ke6ivt6d5hWCQ6cRHRZ8JccqniMjknCvhOU6Fcm?width=667&height=1000&cropmode=none"
    },
    {titulo: "V for Vendetta",
     ano: "2005",
     tamanho: "2h 12min",
     idade: "16",
     desc: "Em um futuro da tirania britânica, um lutador clandestino conhecido como V trama um plano para derrubá-la com a ajuda de uma jovem mulher.",
     img:"https://bn02pap001files.storage.live.com/y4mUlfgJc3SL_k7lksUIw_aYb-1HqyEyniLAJ_-xBIW570QOaGD0InLzVSdO9NEoU1ZVo5ZG6Z7GHMbc2sbFUhqMf6XiyRaISsTlrg-iFwgyGH2ikfwTqydClYIcaXKv6aJ5keQJ1PePqw8iklHqwo0SrwjfdDEnt8Ag9zXOCJv4zSH2nwhT3_1CqRWDoxnc5mJ?width=667&height=1000&cropmode=none"
    },
    {titulo: "Blade Runner",
     ano: "1982",
     tamanho: "1h 57min",
     idade: "14",
     desc: "Um ex-policial do esquadrão de elite tem ordem para caçar um grupo de clones humanos que permanecem na Terra de forma ilegal.",
     img:"https://bn02pap001files.storage.live.com/y4mvJ_Tv9LS_lHjQ9PVyZHW6h6YvQhWkg-Ox2R6mh_2eUs023rrkJp0RVu24QbIEJelhVjfsWW9yt4AOmszSbCnSh_BeDw4hTxnV3_yoxekODdFu0FajDGIBSOLBKur9cEHAJi_HoDQmWm4PKp-txg5_OuVOtcbnn5UPln35vkAhkKgSb6AxCdYRqJgCsFWhh6A?width=667&height=1000&cropmode=none"
    },
    {titulo: "Gran Torino",
     ano: "2008",
     tamanho: "1h 56min",
     idade: "14",
     desc: "Walt Kowalski, um veterano da guerra da Coreia, tenta reformar seu vizinho quando ele tentar lhe roubar sua posse mais amada, um Gran Torino de 1972.",
     img:"https://bn02pap001files.storage.live.com/y4mKnPrnupaKEwUxxuBxeCMp2mYyo_zAx-i3LAIXTGLmmK11F6R2tc7ZlTENU-1TFiDRygxxN9RSmYE0BFRumzfvxR1WCGKupXR8NyqUj6yAr0nF9pnDy7P2okCQBGRdBBGVHmXUGg4B8LwKJUOLgtmW-E6b96htprtroI02wOg4smXeY86SHmcHlyCnNvpZVs4?width=667&height=1000&cropmode=none"
    },
    {titulo: "Mary and Max",
     ano: "2009",
     tamanho: "1h 32min",
     idade: "12",
     desc: "A estranha história de uma amizade entre dois amigos por correspondência: Mary, uma garota solitária de oito anos que vive nos subúrbios de Melbourne, e Max, um homem obeso de quarenta e quatro anos que vive em Nova York.",
     img:"https://bn02pap001files.storage.live.com/y4mbI_YHFb1tz2VBkfVqtONJifgN_4E7KHU7KfGJPpqj3oKAjxK5U5-rKeILroRKtXcyqRmBebbUnpP8nL0L7StXnUGvHy9lyn5KVR2n8GWsEaQEQ2HM8RTPL4PH0IjrIUWZPmmG2dbaBl6qJ1xSv-6sSsHhsMDA0IKComOIh_ASAnJovZ-x_ABMfwVHuBc9fqS?width=667&height=1000&cropmode=none"
    },
    {titulo: "Ford v Ferrari",
     ano: "2019",
     tamanho: "2h 32min",
     idade: "12",
     desc: "Um designer de carros e um motorista combatem a interferência corporativa, as leis da física e seus próprios demônios pessoais para construir um carro de corrida revolucionário para a Ford e desafiar a Ferrari nas 24 Horas de Le Mans em 1966.",
     img:"https://bn02pap001files.storage.live.com/y4m6UiU_EUsf8-XoKMnloZTx3iG80OqY_58P_WeXFNlLw79Dm6uOzg9haLVdolfjkI9ph01sSRckmXITRpjsjLaEZTmQlqxnJozWhN8rxgxDIsJ51XW6aZ-8OK_n5F2VB9BnI6kn3scaeDzqGjeK2saYFxDJa1pNMED1ADcKey1d_jtJkNmB50lKBc0bqGhDddq?width=667&height=1000&cropmode=none"
    },
    {titulo: "Rush",
     ano: "2013",
     tamanho: "2h 3min",
     idade: "14",
     desc: "A história da rivalidade impiedosa nos anos 70 entre os rivais de Fórmula 1 James Hunt e Niki Lauda.",
     img:"https://bn02pap001files.storage.live.com/y4mZU25WcPe_ZVdGuwRhp10TJOpW6kq3R92yIpipjFdh7UzE65IHsj9ogqhh3_aHKv-LCwGF2L20_R1RMUyaTKKNQFNkO-KLNG8taPtvIyQwHlrX4BRqqeMEZnbJOYmImyxrAyhQY2wCMV_HaZjLEUt-8t1PjY_UA-sgrJS8d0ZgS6qsZpR6ptWSqlHPdU_KO1E?width=667&height=1000&cropmode=none"
    },
    {titulo: "The League of Extraordinary Gentlemen",
     ano: "2003",
     tamanho: "1h 50min",
     idade: "12",
     desc: "Na Era Vitoriana de uma linha temporal alternativa, um grupo de heróis vindos das páginas da literatura são reunidos pela Coroa para deter os planos de um terrorista que usa tecnologia avançada para ameaçar a ordem do Império Britânico.",
     img:"https://bn02pap001files.storage.live.com/y4mIgzlMugobxPfkO-HdEHca7WMd59ymZKmFy5ugE6oK4MlI8r64FNXdL8j7nym2u8-sqXGP9qS50Q61Ym2IBiUQO2SfIrpol0IkG4T_oRgNKSnqSlDYnnuHtNDEEB78-GEv8U8Nkq-cOXOsBwstDHnXwF41ZqFgrm9YeACoeV9Plc-Vz3jKR54vSj7mYwBSMd4?width=667&height=1000&cropmode=none"
    },
    {titulo: "Sherlock Holmes",
     ano: "2009",
     tamanho: "2h 8min",
     idade: "14",
     desc: "O detective Sherlock Holmes e seu colega Watson se engajam numa batalha para lutar contra as ameaças da Inglaterra.",
     img:"https://bn02pap001files.storage.live.com/y4mvhJuZG8wKYTb2HNaDdLYujKHlXuyUX-4dL4gmwCAC-ufmuwU0RDQAjVXris0rw8oDottALDwqalAkPhttzhOiMoDFbYrGEmLkowNJJW_Ym4UMAs2z1vfq-y_nqvNwm-Mjg7VKqZLqBgjDbv5TL0hoG1gpm0Bc_9phFxB1J2qaQrPD5vbrxQAq3DHpfpqxdKA?width=667&height=1000&cropmode=none"
    },
    {titulo: "Men in Black 3",
     ano: "2012",
     tamanho: "1h 46min",
     idade: "10",
     desc: "O agente J viaja pelo tempo ao ano 1969 para tentar deter um extraterrestre de assassinar seu amigo o agente K e mudar a historia.",
     img:"https://bn02pap001files.storage.live.com/y4mKUxERqIaBOAURWwf8nE4mbSdM696agL7f45m7DqqyLD2gmK8Ei2xAiZtn-2V2jRuhhZrZNzxoKULbivfx1Uxwo_XFV45-lPou9MMnhUKtBrJhlomVMAx7eDAGq9Xmbh9a15ZM8z-Z8Q036y9lx7Aesy5JyT7vtlQD6M1HCwn014kXqCXtwsT-bW-GhXSbe9f?width=667&height=1000&cropmode=none"
    }
];